### ISSUE TITLE
Не работает с АС "УРМ" 14.30.00

### ISSUE THREAD

**Issue by CAHbKA-IV** [Etersoft/wine-cpcsp_proxy#2]
При обращении к криптопровайдеру наблюдается следующее сообщение об ошибке:
ICryptProviders.Initialize.AddProviderAlgorithms:CryptAcquireContext(Crypto Pro GOST 34.10-2001 Cryptographic Service Provider, 75) - [API Error: 2148073501] {#0049#}.

Код ошибки:
0x8009001D L          NTE_PROVIDER_DLL_FAIL     The provider DLL file could not be loaded or failed to initialize.

Вывод в консоли Wine при обращении к криптопровайдеру:
0368:fixme:crypt:CRYPT_LoadProvider Failed to load dll L"cpcsp_proxy.dll"
0368:fixme:ole:CoCreateInstanceEx no instance created for interface {00000000-0000-0000-c000-000000000046} of class {43f63fef-0d12-42e7-b546-4cf7f6c8b79b}, hr 0x8000ffff

cpcsp_proxy_setup проходит корректно.

ОС Astra Linux SE 1.7, Wine 7.3

**Comment by vitlav** [comment]
Проверьте, куда ставятся собранные cpcsp_proxy.dll.so — возможно, что у вас не совпали пути с wine. После обновления префикса cpcsp_proxy.dll должен появиться в windows/system32.
Вам лучше обратиться в support@etersoft.ru, чтобы получить полноценную поддержку.

**Comment by CAHbKA-IV** [comment]
Проблема возникла из-за того, что префикс был создан до установки cpcsp_proxy. Соответственно, библиотека не была скопирована в каталоги system32 и syswow64 внутри префикса.
Если положить библиотеку в префикс вручную, либо пересоздать префикс wine, приложения обнаруживают библиотеку и работают.
